### ISSUE TITLE
Question about getting the result of each splicing iteration

### ISSUE THREAD

**Issue by Everglow00** [abess-team/abess#301]
Hello! I want to get the result of each step of splicing iteration, but I don't know how to get it. The c++ code is difficult for me, I wonder if there is a simple way to get the result?

**Comment by Mamba413** [comment]
Hi~

The splicing iteration is hidden for users because, in applications, it is not essential.  If you really when to assess this, I recommend setting `max.splicing.iter` from 1 to a pre-specified value. An example under linear regression for `abess` R package is:
```r
library(abess)
n <- 50
p <- 300
support.size <- 10

dataset <- generate.data(n, p, support.size, cortype = 3, rho = 0.9, seed = 1234)
for (i in 1:3) {
  abess_fit <- abess(dataset[["x"]], dataset[["y"]], 
                     support.size = support.size, 
                     max.splicing.iter = i)
  print(extract(abess_fit)[["support.vars"]])
}
```
The above code prints each step of splicing iteration:
```r
 [1] "x12"  "x29"  "x39"  "x63"  "x110" "x116" "x164" "x165" "x215" "x240"
 [1] "x29"  "x63"  "x105" "x110" "x116" "x164" "x165" "x215" "x240" "x264"
 [1] "x29"  "x63"  "x105" "x110" "x116" "x164" "x165" "x215" "x240" "x264"
```
We can see that a few iterations lead to convergence. 

If you still have any questions, free feel to contact us.
