### ISSUE TITLE
Unexpected NaN produced when fitting logistic regression.

### ISSUE THREAD

**Issue by brtang63** [abess-team/abess#314]
**Describe the bug**

Unexpected NaN appears in regression coefficients when fitting logistic regression on a real data.

**Code for Reproduction**
```r
library(abess)
x_train <- as.matrix(read.table("arcene_train.txt"))
y_train <- (read.table("arcene_train_labels.txt")$V1 + 1) / 2
fit_abess <- abess(x_train, y_train, family = "binomial")
beta <- coef(fit_abess, fit_abess$best.size)
sum(is.nan(as.vector(beta)))
```

**Issue**
The coefficient contains NaNs, which is not expected, since there is no NA or NaN in the data, which can be easily checked via
```r
sum(is.na(x_train))
sum(is.na(y_train))
sum(is.nan(x_train))
sum(is.nan(y_train))
```

 

**Desktop**
 - OS: Windows10
 - R Version: 4.0.5
 - Package Version: 0.3.0
 
**Dataset**

[arcene_train.txt](https://github.com/abess-team/abess/files/7905429/arcene_train.txt)
[arcene_train_labels.txt](https://github.com/abess-team/abess/files/7905433/arcene_train_labels.txt)

**Comment by oooo26** [comment]
I find that although there is no NA or NAN in the data, some columns are all zeros.
Since we did not take this situation into account, NANs will be caused during the normalization in abess.

Each NAN indicates an "all-zero" column:
```r
temp <- is.nan(as.vector(beta)[-1])
nan_pos <- which(temp)
sum(x_train[,nan_pos]!=0)
# output: 0
```

But it reminds us to add an warning for this situation. Thanks for your comment!
