### ISSUE TITLE
Is it possible to combine `group` and `always_select` to always select a whole group?

### ISSUE THREAD

**Issue by MattWenham** [abess-team/abess#503]
If we wish to use `always_select` to select an entire `group` of targets, how should this be done? I can imagine two possibilities:

1. Apply `always_select` to _all_ members of the group, or
2. Apply `always_select` to _any_ member of the group.

Which of these should work correctly?

**Comment by oooo26** [comment]
Hi @MattWenham, actually, when `group` is specified, the value in `always_select` indicates **group number** instead of variable.

It might be more clear with an example:
```python
import numpy as np
import abess
np.random.seed(1)

# build data
n = 300
p = 30
group_size = 5
k = 3 * group_size

coef_real = np.repeat([0., .1, 0., 1., 0., 10.], group_size)  # real coefficients
group = np.repeat([0, 1, 2, 3, 4, 5], group_size)             # group info

data = abess.make_glm_data(
    n=n, p=p, k=k, family="gaussian",
    coef_ = coef_real)
data.coef_
```

We split the coefficients into 6 groups, where each contains 5 variables and only the second, fourth, sixth groups are non-zero. The fitting code would be:
```python
model = abess.LinearRegression(
    support_size=range(p // group_size),  # max sparsity: p // group_size = 6
    group=group
)
model.fit(data.x, data.y)
model.coef_
```

It may ignore the second group because $0.1$ is not significant. So we can add it with `always_select`:
```python
model1 = abess.LinearRegression(
    support_size=range(p // group_size),
    always_select=[1],  # always select the second group (group number starts from 0)
    group=group
)
model1.fit(data.x, data.y)
model1.coef_
```

Now all real non-zero groups are chosen correctly. Hope this can help u.

**Comment by oooo26** [comment]
> Okay, so when using `group` then `always_select` applies to the _group number_. This should probably be added to the documentation 👍🏻

Thank you for the advice! We will update that.
